apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-planner-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: travel-planner
  template:
    metadata:
      labels:
        app: travel-planner
    spec:
      containers:
      - name: travel-planner
        image: jkz3/travel-planner-apache  
        ports:
        - containerPort: 80
